# Markdownlint configuration for Spring PetClinic

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013: false

# MD033/no-html-html - HTML elements
MD033:
  allowed_elements:
    - br
    - div
    - span
    - sub
    - sup
    - marker1
    - marker2
    - marker3
    - response

# MD041/first-line-heading/first-line-h1 - First line should be a heading
MD041: false

# MD034/no-bare-urls - Bare URLs
MD034: false

# MD046/code-fence-style - Code fence style
MD046:
  style: fenced

# MD048/code-block-style - Code block style
MD048: false

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2

# MD009/no-trailing-spaces - Trailing spaces
MD009: true

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: false

# MD022/blanks-around-headings - Headings should be surrounded by blank lines
MD022: true

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with same content
MD024:
  allow_different_nesting: true

# MD025/single-title/single-h1 - Multiple top-level headings
MD025:
  front_matter_title: '^\\s*title\\s*[:=]'

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: ordered

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: true

# MD036/emphasis-as-emphasis - Emphasis used instead of heading
MD036:
  punctuation: ".,;:!?。，；：！"

# MD037/no-space-in-emphasis - Spaces inside emphasis markers
MD037: true

# MD038/no-space-in-code - Spaces inside code span elements
MD038: true

# MD040/fenced-code-language - Fenced code blocks should have a language
MD040: true

# MD042/no-empty-links - No empty links
MD042: true

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  code_blocks: false
  names:
    - JavaScript
    - TypeScript
    - Node.js
    - GitHub
    - GitLab
    - Docker
    - Kubernetes
    - Spring Boot
    - Maven
    - Gradle
    - JUnit
    - Mockito
    - JaCoCo
    - Checkstyle
    - SpotBugs
    - SonarQube

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: true

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true
