import { test, expect } from '@fixtures/base-test';

import { OwnerPage } from '@pages/owner-page';
import { createPet } from '@utils/pet-factory';

test.describe('Pet Management', () => {
  test('can add a pet to an existing owner and see it on owner details', async ({ page }) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'cat' });

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Form fields are generated by thymeleaf fragments: ids match field names
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });

    await page.screenshot({ path: 'test-results/pet-add-form-filled.png', fullPage: true });

    await page.getByRole('button', { name: /Add Pet/i }).click();

    // Back on owner details
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Add a visit for the newly-created pet and verify it shows under visit history.
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name })
    });

    await petRow.getByRole('link', { name: /Add Visit/i }).first().click();

    await page.locator('input#date').fill('2024-01-01');
    await page.locator('input#description').fill('Annual checkup');
    await page.screenshot({ path: 'test-results/visit-add-form-filled.png', fullPage: true });
    await page.getByRole('button', { name: /Add Visit/i }).click();

    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: '2024-01-01', exact: true })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: 'Annual checkup', exact: true })).toBeVisible();

    await page.screenshot({ path: 'test-results/pet-details-with-visit-history.png', fullPage: true });
  });

  test('validates pet type selection and birth date format', async ({ page }) => {
    const ownerPage = new OwnerPage(page);

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Validate required fields (observable via UI): leave name and birth date empty.
    await page.locator('select#type').selectOption({ index: 0 });
    await page.getByRole('button', { name: /Add Pet/i }).click();

    await expect(page.locator('.help-inline').filter({ hasText: /is required/i })).toHaveCount(2);
  });
});
