import { fileURLToPath } from 'url';

import { test, expect } from '@fixtures/base-test';

import { OwnerPage } from '@pages/owner-page';
import { PetPage } from '@pages/pet-page';
import { createPet } from '@utils/pet-factory';
import { futureDate } from '@utils/test-helpers';

test.describe('Pet Management', () => {
  test('can add a pet to an existing owner and see it on owner details', async ({ page }, testInfo) => {
    const ownerPage = new OwnerPage(page);
    const pet = createPet({ type: 'cat' });

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Form fields are generated by thymeleaf fragments: ids match field names
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });

    await page.screenshot({ path: testInfo.outputPath('pet-add-form-filled.png'), fullPage: true });

    await page.getByRole('button', { name: /Add Pet/i }).click();

    // Back on owner details
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Add a visit for the newly-created pet and verify it shows under visit history.
    const petRow = page.locator('tr').filter({
      has: page.locator('dd', { hasText: pet.name })
    });

    await petRow.getByRole('link', { name: /Add Visit/i }).first().click();

    const visitDate = futureDate();
    await page.locator('input#date').fill(visitDate);
    await page.locator('input#description').fill('Annual checkup');
    await page.screenshot({ path: testInfo.outputPath('visit-add-form-filled.png'), fullPage: true });
    await page.getByRole('button', { name: /Add Visit/i }).click();

    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: visitDate, exact: true })).toBeVisible();
    await expect(petRow.getByRole('cell', { name: 'Annual checkup', exact: true })).toBeVisible();

    await page.screenshot({ path: testInfo.outputPath('pet-details-with-visit-history.png'), fullPage: true });
  });

  test('can delete a pet with no visit history and verify it is removed', async ({ page }) => {
    const ownerPage = new OwnerPage(page);
    const petPage = new PetPage(page);
    const pet = createPet({ type: 'cat' });

    // Navigate to Betty Davis's owner details page
    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    // Add a new pet with no visit history
    await page.getByRole('link', { name: /Add New Pet/i }).click();
    await page.locator('input#name').fill(pet.name);
    await page.locator('input#birthDate').fill(pet.birthDate);
    await page.locator('select#type').selectOption({ label: pet.type });
    await page.getByRole('button', { name: /Add Pet/i }).click();

    // Verify the pet appears on the owner details page
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.getByText(pet.name, { exact: true })).toBeVisible();

    // Click the Delete Pet button — modal should appear
    await petPage.clickDeletePetButton(pet.name);

    // Wait for the modal to be visible, then capture a screenshot as proof artifact
    await expect(page.locator('#deletePetModal')).toBeVisible();
    const screenshotPath = fileURLToPath(
      new URL(
        '../../../docs/specs/05-spec-delete-pet/05-proofs/05-delete-pet-confirmation-modal.png',
        import.meta.url
      )
    );
    await page.screenshot({ path: screenshotPath, fullPage: false });

    // Confirm deletion
    await petPage.confirmDeletion();

    // Assert redirect back to owner details with success flash message
    await expect(page.getByRole('heading', { name: /Pets and Visits/i })).toBeVisible();
    await expect(page.locator('#success-message')).toBeVisible();

    // Assert the deleted pet no longer appears on the page
    await expect(page.getByText(pet.name, { exact: true })).not.toBeVisible();
  });

  test('validates pet type selection and birth date format', async ({ page }) => {
    const ownerPage = new OwnerPage(page);

    await ownerPage.openFindOwners();
    await ownerPage.searchByLastName('Davis');
    await ownerPage.openOwnerDetailsByName('Betty Davis');

    await page.getByRole('link', { name: /Add New Pet/i }).click();

    // Validate required fields (observable via UI): leave name and birth date empty.
    await page.locator('select#type').selectOption({ index: 0 });
    await page.getByRole('button', { name: /Add Pet/i }).click();

    await expect(page.getByText(/is required/i)).toHaveCount(2);
  });
});
